server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: helpdesk
  flyway:
    enable: true
    baseline-on-migrate: false
    location: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/helpdesk
    username: postgres
    password: 123